### ISSUE TITLE
Hands don't hold position when moving HMD

### ISSUE THREAD

**Issue by martinboerma** [getnamo/leap-ue4#16]
Hi,

Trying out the LeapMotion plugin in UE4. The hands show and work. But when turning HMD from left to right the hands seem to have trouble staying in place, they jitter. Sometimes they move with the HMD and jump back to their position. In the LeapMotion vizualizer they stay in place when turning HMD left/right.

I did a screen recording but found out that the jitter does not show in the VR preview window. Only on the HMD screen itself.

Is this a know issue?

Here's a [screenrecording] (https://dl.dropboxusercontent.com/u/31337897/bugs/UE4%20LeapMotion%20plugin.mp4)

Setup: Ue4.14.1 / Rift CV1 / Leap controller firmware v1.7 / Orion 3.2.0 / GTX1080

UPDATE: I'll move this question to the UE4 forum. 

Cheers,
Martin

**Comment by getnamo** [comment]
That has to do with the unreal plugin lacking proper timewarp (different from HMD timewarp) support (https://github.com/getnamo/leap-ue4/issues/9). This is a math transform that uses leap tracking time samples and headset positions near those times and compares the rotation since that time and updates all the positions to the headset PoV so that you are in sync with the headset. See https://community.leapmotion.com/t/unreal-plugin-latency/5791/5 for discussion on this. I've attempted to use implement this, but it never worked without jitter so something is still missing.

I'll take another crack at this when it comes to the modern rewrite of the plugin.

Or maybe someone smarter than me can crack the problem before then :)
